#!/bin/bash
set -e -o pipefail
SCRIPT="${0##*/}"
# shellcheck disable=SC2034
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"
VERSION='1.0.20260725a'
trap 'echo "ERROR[${SCRIPT}]: Internal error" >&2' ERR


## Defaults
: "${PI_STATION_IMG_URL:=https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2026-06-19/2026-06-18-raspios-trixie-arm64-lite.img.xz}"
: "${PI_STATION_IMG_HASH:=acff736ca7945e3b305f07cda4abdb870910e12634991da69783611756e381b3}"
: "${PI_STATION_QEMU_DIR:=./qemu-raspi3b.data}"
: "${PI_STATION_QEMU_VNC:=127.0.0.1:0}"
: "${PI_STATION_QEMU_SSH:=2222}"


## Helpers

# Usage
__USAGE() {
  cat >&2 << EOF
USAGE: ${SCRIPT} [<options>]

SYNOPSIS:
  Launch the 64-bit Raspberry Pi QEMU emulation (aarch64/raspi3b) after
  downloading and preparing the Raspberry Pi OS image accordingly.

  REQUIRES sudo privileges (to mount the Raspberry Pi image and extract
  its kernel/DTB).

OPTIONS:
  -h, --help
    Display this usage information and exit
  -v, --version
    Display this script version and exit
  --verbose, --silent
    Increase or decrease verbosity
  --inspect
    Allow to inspect the Rapsberry Pi image once mounted
EOF
}

# Input/Output
__INFO() {
  [ -n "${OPT_VERBOSE}" ] && echo "INFO[${SCRIPT}]: ${1}"
  return 0
}

__NOTICE() {
  [ -z "${OPT_SILENT}" ] && echo "NOTICE[${SCRIPT}]: ${1}"
  return 0
}

__WARNING() {
  echo "WARNING[${SCRIPT}]: ${1}" >&2
  return 0
}

__ERROR() {
  echo "ERROR[${SCRIPT}]: ${1}" >&2
  [ -n "${2}" ] && exit "${2}"
  return 0
}

__PROMPT() {
  prompt="PROMPT[${SCRIPT}] ${1}"
  input=
  while true; do
    read -rp "${prompt} [yes/No] ? " input
    case "${input:0:1}" in
    'Y'|'y') return 0;;
    'N'|'n'|'') return 1;;
    esac
  done
}

__OPTION() {
  [ -z "${2}" ] && __ERROR "Missing option argument (${1})" 1
  return 0
}


## Arguments
while [ -n "${1}" ]; do
  case "${1}" in
    '-h'|'--help')
      __USAGE; exit 0
      ;;
    '-v'|'--version')
      echo "${SCRIPT} ${VERSION}"; exit 0
      ;;
    '--verbose')
      OPT_VERBOSE='yes'; OPT_SILENT=
      ;;
    '--silent')
      OPT_SILENT='yes'; OPT_VERBOSE=
      ;;
    '--inspect')
      OPT_INSPECT='yes'
      ;;
    -*)
      __ERROR "Invalid option (${1})" 1
      ;;
    *)
      __ERROR "Too many arguments (${1})" 1
      ;;
  esac
  shift
done
if [ -n "${OPT_INSPECT}" ]; then
  set +e
fi


## Main

# Data directory
mkdir -p "${PI_STATION_QEMU_DIR}"

# Download image
download="${PI_STATION_QEMU_DIR}/${PI_STATION_IMG_URL##*/}"
if [ -e "${download}" ] && __PROMPT "The Raspberry Pi OS image download already exists (${download##*/}); do you want to replace it"; then
  rm -f "${download}"
fi
if [ ! -e "${download}" ]; then
  __NOTICE "Downloading Raspberry Pi OS image (${PI_STATION_IMG_URL})"
  wget "${PI_STATION_IMG_URL}" -O "${download}"
  if ! echo "${PI_STATION_IMG_HASH}  ${download}" | sha256sum --quiet --check; then
    rm -f "${download}"
    __ERROR "Failed to verify Raspberry Pi OS image hash (${PI_STATION_IMG_HASH})" 1
  fi
fi

# Create image
image="${PI_STATION_QEMU_DIR}/raspi3b.img"
if [ -e "${image}" ] && __PROMPT "The Raspberry Pi OS image already exists (${image##*/}); do you want to (sudo-)replace it"; then
  rm -f "${image}"
fi
if [ ! -e "${image}" ]; then
  __NOTICE "Creating the Raspberry Pi OS image"
  extension="${PI_STATION_IMG_URL##*.}"
  case "${extension}" in
    'xz') xzcat "${download}" > "${image}";;
    'bz2') bzcat "${download}" > "${image}";;
    'gz') gzcat "${download}" > "${image}";;
    'img'): cat "${download}" > "${image}";;
    *) __ERROR "Unsupported image format (${extension})" 1;;
  esac
  qemu-img resize -f raw "${image}" 8G  # Or QEMU will complain about SD card size

  __INFO "Mounting the Raspberry Pi OS root partition"
  mountpoint="${PI_STATION_QEMU_DIR}/raspi3b.mnt"
  mkdir -p "${mountpoint}"
  devloop="$(sudo losetup --show -Pf "${image}")"
  # shellcheck disable=SC2064
  trap "sudo losetup -d '${devloop}'" EXIT
  sudo mount "${devloop}p2" "${mountpoint}"
  # shellcheck disable=SC2064
  trap "sudo umount '${mountpoint}'; sudo losetup -d '${devloop}'" EXIT

  # BUG: "mkinitramfs: failed to determine device for /"
  # QUIRK: Enable most filesystems modules in initramfs
  __NOTICE "Configuring initramfs to use most filesystems modules"
  sudo sed -i -E 's|^MODULES=.*|MODULES=most|' /etc/initramfs-tools/initramfs.conf

  # BUG: https://forums.raspberrypi.com/viewtopic.php?t=399519
  # QUIRK: Explicitly mange the UBS network device using ifupdown
  __NOTICE "Configuring NetworkManager to manage legacy (ifupdown) interfaces"
  cat <<EOF | sudo tee "${mountpoint}/etc/NetworkManager/NetworkManager.conf"
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=true
EOF
  __NOTICE "Configuring USB0 (ifupdown) interface (DHCP <-> QEMU Slirp)"
  cat <<EOF | sudo tee "${mountpoint}/etc/network/interfaces"
auto usb0
iface usb0 inet dhcp
EOF

  if [ -n "${OPT_INSPECT}" ]; then
    __NOTICE "The Raspberry Pi OS root partition is mounted at: ${mountpoint}"
    __NOTICE "PRESS <ENTER> ONCE DONE INSPECTING IT"
    read -r
  fi

  __INFO "Unmounting the Raspberry Pi OS root partition"
  sudo umount "${mountpoint}"
  sudo losetup -d "${devloop}"
  trap EXIT
fi

# Prepare QEMU boot
qemudir="${PI_STATION_QEMU_DIR}/raspi3b.qemu"
if [ -e "${qemudir}" ] && __PROMPT "The Raspberry Pi OS QEMU boot directory already exists (${qemudir##*/}); do you want to (sudo-)replace it"; then
  rm -rf "${qemudir}"
fi
if [ ! -e "${qemudir}" ]; then
  __INFO "Mounting the Raspberry Pi OS boot partition"
  mountpoint="${PI_STATION_QEMU_DIR}/raspi3b.mnt"
  mkdir -p "${mountpoint}"
  devloop="$(sudo losetup --show -Pf "${image}")"
  # shellcheck disable=SC2064
  trap "sudo losetup -d '${devloop}'" EXIT
  sudo mount "${devloop}p1" "${mountpoint}"
  # shellcheck disable=SC2064
  trap "sudo umount '${mountpoint}'; sudo losetup -d '${devloop}'" EXIT

  if sudo grep -qE '(serial0|quiet)' "${mountpoint}/cmdline.txt"; then
    __NOTICE "Fine-tuning the Raspberry Pi OS boot configuration: kernel parameters"
    sudo sed -i -E 's|serial0\S*|ttyAMA0|;s|\s+quiet||' "${mountpoint}/cmdline.txt"
  fi

  if [ ! -e "${mountpoint}/userconf.txt" ]; then
    __NOTICE "Fine-tuning the Raspberry Pi OS boot configuration: user"
    password=
    password_confirm='yes'
    while [ "${password}" != "${password_confirm}" ]; do
        read -srp "Enter new password for 'pi' user: " password
        echo
        read -srp "Confirm new password for 'pi' user: " password_confirm
        echo
    done
    password="$(echo "${password}" | mkpasswd -s -m yescrypt -R 6)"
    echo "pi:${password}" | sudo tee "${mountpoint}/userconf.txt" >/dev/null
    sudo touch "${mountpoint}/ssh"
  fi

  __NOTICE "Extracting the Raspberry Pi OS kernel and DTB"
  mkdir -p "${qemudir}"
  for f in kernel8.img bcm2710-rpi-3-b-plus.dtb cmdline.txt; do
    sudo cp -v "${mountpoint}/${f}" "${qemudir}/${f}"
    sudo chmod o+r "${qemudir}/${f}"
  done

  if [ -n "${OPT_INSPECT}" ]; then
    __NOTICE "The Raspberry Pi OS boot partition is mounted at: ${mountpoint}"
    __NOTICE "PRESS <ENTER> ONCE DONE INSPECTING IT"
    read -r
  fi

  __INFO "Unmounting the Raspberry Pi OS boot partition"
  sudo umount "${mountpoint}"
  sudo losetup -d "${devloop}"
  trap EXIT
fi
cmdline="$(cat "${qemudir}/cmdline.txt")"

# Selecting the DTB
dtbdir="${SCRIPT_DIR}/dtb"
if [ ! -e "${qemudir}/raspi3b.dtb" ]; then
  if __PROMPT "Use the stock DTB (instead of the QEMU-specific one)"; then
    ln -s bcm2710-rpi-3-b-plus.dtb "${qemudir}/raspi3b.dtb"
  else
    ln -s "${dtbdir}/bcm2710-rpi-3-b-plus-qemu.dtb" "${qemudir}/raspi3b.dtb"
  fi
fi

# Launching the QEMU-lation
# NB:
# * -no-reboot is required:
#   - to avoid kernel panic on first reboot
#   - have host (SSH) port forwarding (almost) always work (QEMU BUG ?)
# * systemd.watchdog_device=/dev/null is required:
#   - to disable systemd watchdog, which kills the (QEMU) boot process early on
__NOTICE "About to launch the Rapsberry Pi OS QEMU-lation; you may:"
__NOTICE "- use <CTRL+A>+<C> to enter the QEMU prompt"
__NOTICE "- use VNC to access the console; e.g. gvncviewer 127.0.0.1:${PI_STATION_QEMU_VNC##*:}"
__NOTICE "- use SSH to access the command prompt; e.g. ssh -p ${PI_STATION_QEMU_SSH} pi@127.0.0.1"
__PROMPT "Skip launching the Raspberry Pi OS QEMU-lation now" && exit
qemu-system-aarch64 \
  -M raspi3b \
  -no-reboot \
  -smp 4 \
  -m 1024 \
  -dtb "${qemudir}/raspi3b.dtb" \
  -kernel "${qemudir}/kernel8.img" \
  -append "${cmdline} dwc_otg.lpm_enable=0 systemd.watchdog_device=/dev/null" \
  -drive if=sd,file="${PI_STATION_QEMU_DIR}/raspi3b.img",format=raw \
  -device usb-kbd \
  -device usb-net,netdev=net0 \
  -netdev "user,id=net0,ipv4=on,hostfwd=tcp::${PI_STATION_QEMU_SSH}-:22" \
  -serial mon:stdio \
  -vnc "${PI_STATION_QEMU_VNC}" \
|| true
