---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Playbook
- name: "Random Number Generator (RNG) Daemon setup"
  hosts: all
  roles:
   - ../rngd
