---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Audio setup: disable

- name: "Disable audio hardware"
  tags:
    - audio
    - configure
  lineinfile:
    path: "/boot/config.txt"
    regexp: "^#?dtparam=audio"
    line: "dtparam=audio=off"

- name: "Uninstall audio packages"
  tags:
    - audio
    - install
  apt:
    state: absent
    purge: true
    autoremove: true
    name:
      #- alsa-utils  # required by raspi-config
      - alsa-tools
