---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Cleanup orphaned packages

- name: "Find orphaned packages"
  tags:
    - cleanup
    - deborphan
  shell: |
    set -o pipefail
    readarray -tu3 depends 3< <(
      apt-cache depends --installed '*' \
      | sed -nE 's#^.*Depends:\s+##p' \
      | sort -u
    )
    readarray -tu3 candidates 3< <(
      cat \
      <(apt-mark showauto '^lib.*' '^python3?-.*' '.*-common$' '.*-data$' '.*-dbg$' '.*-dev$')\
      <(apt-mark showmanual '^lib.*') \
      | sort -u
    )
    join -v1 \
    <(printf '%s\n' "${candidates[@]}") \
    <(printf '%s\n' "${depends[@]}")
  register: cleanup_deborphan
  changed_when: false

- name: "Remove orphaned packages"
  tags:
    - cleanup
    - deborphan
  apt:
    state: absent
    purge: true
    autoremove: true
    name: "{{ cleanup_deborphan.stdout_lines }}"
  check_mode: false

- name: "Cleanup orphaned packages: LOOP"
  tags:
    - cleanup
    - deborphan
  include_tasks: "deborphan.yaml"
  when: not ansible_check_mode and cleanup_deborphan.stdout_lines | length
