---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Playbook
- name: "Raspberry Pi OS Testing Repository setup"
  hosts: all
  roles:
   - ../raspi_testing
