---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Time Synchronization setup

- name: "Time Synchronization setup"
  tags:
    - timesyncd
    - always
  include_tasks:
    file: "{{ TIMESYNCD_ENABLE|bool | ternary('enable.yaml', 'disable.yaml') }}"
