---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Sleepy Pi setup: disable

- name: "Stop Sleepy Pi (agent) service"
  tags:
    - sleepypi
    - service
  service:
    name: "sleepy-pi-agent"
    state: stopped
  ignore_errors: true

- name: "Stop Sleepy Pi (watchdog) service"
  tags:
    - sleepypi
    - service
  service:
    name: "sleepy-pi-watchdog"
    state: stopped
  ignore_errors: true

- name: "Stop Sleepy Pi (sunwatch) service"
  tags:
    - sleepypi
    - service
  service:
    name: "sleepy-pi-sunwatch"
    state: stopped
  ignore_errors: true

- name: "Uninstall Sleepy Pi (agent) service"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    dest: "/etc/systemd/system/sleepy-pi-agent.service"

- name: "Uninstall Sleepy Pi (watchdog) service"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    dest: "/etc/systemd/system/sleepy-pi-watchdog.service"

- name: "Uninstall Sleepy Pi (sunwatch) service"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    dest: "/etc/systemd/system/sleepy-pi-sunwatch.service"

- name: "Unconfigure Sleepy Pi (watchdog) service"
  tags:
    - sleepypi
    - configure
  file:
    state: absent
    name: "/etc/default/sleepy-pi-watchdog"

- name: "Unconfigure Sleepy Pi (sunwatch) service"
  tags:
    - sleepypi
    - configure
  file:
    state: absent
    name: "/etc/default/sleepy-pi-sunwatch"

- name: "Uninstall Sleepy Pi (client) script"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    name: "/usr/local/bin/sleepy-pi"

- name: "Uninstall Sleepy Pi (agent) script"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    name: "/usr/local/bin/sleepy-pi-agent"

- name: "Uninstall Sleepy Pi (watchdog) script"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    name: "/usr/local/bin/sleepy-pi-watchdog"

- name: "Uninstall Sleepy Pi (sunwatch) script"
  tags:
    - sleepypi
    - install
  file:
    state: absent
    name: "/usr/local/bin/sleepy-pi-sunwatch"
