---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Huawei HiLink setup: disable

- name: "Unconfigure Huawei HiLink repository preferences"
  tags:
    - huawei_hilink
    - configure
  file:
    state: absent
    dest: "/etc/apt/preferences.d/huawei-hilink.pref"

- name: "Uninstall Huawei HiLink repository key"
  tags:
    - huawei_hilink
    - install
  file:
    state: absent
    dest: "/etc/apt/keyrings/salamek.gpg"

- name: "Uninstall Huawei HiLink repository"
  tags:
    - huawei_hilink
    - install
  deb822_repository:
    state: absent
    name: "huawei-hilink"

- name: "Uninstall Huawei HiLink control script"
  tags:
    - huawei_hilink
    - install
  file:
    state: absent
    name: "/usr/local/bin/huawei-hilink"

- name: "Unconfigure Huawei HiLink control script"
  tags:
    - huawei_hilink
    - configure
  file:
    state: absent
    name: "/etc/huawei-hilink.conf"

- name: "Unconfigure Huawei HiLink interface name (eth1)"
  tags:
    - huawei_hilink
    - configure
  file:
    state: absent
    name: "/etc/udev/rules.d/80-huawei-hilink.rules"

- name: "Unconfigure Huawei HiLink DHCP hook (dhcpcd)"
  tags:
    - huawei_hilink
    - configure
  file:
    state: absent
    name: "/usr/lib/dhcpcd/dhcpcd-hooks/90-huawei-hilink"

- name: "Unconfigure Huawei HiLink DHCP hook (NetworkManager)"
  tags:
    - huawei_hilink
    - configure
  file:
    state: absent
    name: "/etc/dhcp/dhclient-exit-hooks.d/huawei-hilink"

- name: "Unconfigure Huawei HiLink interface (NetworkManager)"
  tags:
    - huawei_hilink
    - configure
  file:
    state: absent
    name: "/etc/NetworkManager/system-connections/huawei-hilink.nmconnection"

- name: "Uninstall Huawei HiLink packages"
  tags:
    - huawei_hilink
    - install
  apt:
    state: absent
    purge: true
    autoremove: true
    name:
      - python3-huawei-lte-api
