---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## Huawei HiLink setup: enable

- name: "Configure Huawei HiLink repository preferences"
  tags:
    - huawei_hilink
    - configure
  copy:
    src: "huawei-hilink.pref"
    dest: "/etc/apt/preferences.d/huawei-hilink.pref"
    owner: "root"
    group: "root"
    mode: 0o0644

# Adam Schubert (https://www.salamek.cz) APT repository
# REF: https://repository.salamek.cz/
- name: "Install Huawei HiLink repository key"
  tags:
    - huawei_hilink
    - install
  get_url:
    url: "https://repository.salamek.cz/deb/salamek.gpg"
    dest: "/etc/apt/keyrings/salamek.gpg"
    checksum: "sha256:f8401ed3b134c66af5301c81f1419e0027dff15dc907b1ebfde1fda67009f542"
    owner: "root"
    group: "root"
    mode: 0o644

- name: "Install Huawei HiLink repository"
  tags:
    - huawei_hilink
    - install
  deb822_repository:
    name: "huawei-hilink"
    types: "deb"
    uris: "https://repository.salamek.cz/deb/pub"
    signed_by: "/etc/apt/keyrings/salamek.gpg"
    suites: "all"
    components: "main"
    architectures: "arm64"
  register: huawei_hilink_deb822_repository

- name: "Install Huawei HiLink packages"
  tags:
    - huawei_hilink
    - install
  apt:
    update_cache: "{{ huawei_hilink_deb822_repository.changed }}"
    name:
      - python3-huawei-lte-api
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Install Huawei HiLink dependencies"
  tags:
    - huawei_hilink
    - install
  apt:
    state: present
    name:
      - python3-toml
      - usb-modeswitch

- name: "Install Huawei HiLink control script"
  tags:
    - huawei_hilink
    - install
  get_url:
    url: "https://raw.githubusercontent.com/cedric-dufour/scriptisms/master/system/huawei-hilink.py"
    dest: "/usr/local/bin/huawei-hilink"
    owner: "root"
    group: "root"
    mode: 0755

- name: "Configure Huawei HiLink control script"
  tags:
    - huawei_hilink
    - configure
  template:
    src: "huawei-hilink.conf.j2"
    dest: "/etc/huawei-hilink.conf"
    owner: "root"
    group: "root"
    mode: 0640

- name: "Configure Huawei HiLink interface name (eth1)"
  tags:
    - huawei_hilink
    - configure
  template:
    src: "huawei-hilink.udev.rules.j2"
    dest: "/etc/udev/rules.d/80-huawei-hilink.rules"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Check whether the DHCP Client Daemon (dhcpcd) is installed"
  tags:
    - huawei_hilink
    - configure
  stat:
    path: "/usr/lib/dhcpcd/dhcpcd-hooks"
  register: huawei_hilink_dhcpcd

- name: "Configure Huawei HiLink DHCP hook (dhcpcd)"
  tags:
    - huawei_hilink
    - configure
  template:
    src: "huawei-hilink.dhcpcd.j2"
    dest: "/usr/lib/dhcpcd/dhcpcd-hooks/90-huawei-hilink"
    owner: "root"
    group: "root"
    mode: 0644
  when: huawei_hilink_dhcpcd.stat.exists

- name: "Check whether NetworkManager is installed"
  tags:
    - huawei_hilink
    - configure
  stat:
    path: "/etc/NetworkManager/system-connections"
  register: huawei_hilink_network_manager

- name: "Configure Huawei HiLink interface (NetworkManager)"
  tags:
    - huawei_hilink
    - configure
  template:
    src: "huawei-hilink.nmconnection.j2"
    dest: "/etc/NetworkManager/system-connections/huawei-hilink.nmconnection"
    owner: "root"
    group: "root"
    mode: 0600
  when: huawei_hilink_network_manager.stat.exists

- name: "Configure Huawei HiLink DHCP hook (NetworkManager)"
  tags:
    - huawei_hilink
    - configure
  template:
    src: "huawei-hilink.dhclient.hook.j2"
    dest: "/etc/dhcp/dhclient-exit-hooks.d/huawei-hilink"
    owner: "root"
    group: "root"
    mode: 0644
  when: huawei_hilink_network_manager.stat.exists
