---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
- name: "Pi Station base/common components installation"
  hosts:
    - all
  roles:
    - hostname
    - timezone
    - bash
    - ramoverlay
    - ipv6
    - iptables
    - networkmanager
    - dhcpcd
    - ethernet
    - wlan
    - huawei_hilink
    - rngd
    - timesyncd
    - ntp
    - wireguard
    - freedns
    - inadyn
    - bluetooth
    - audio
    - v4l
    - reboot
    - done
