---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
- name: "Vanilla Raspberry Pi OS installation clean up"
  hosts:
    - all
  roles:
    - cleanup
