---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
- name: "Sleepy Pi installation"
  hosts:
    - all
  roles:
    - i2c
    - pcf8523
    - sleepypi
    - done
