#!/bin/sh
SELF_DIR="$(realpath -e "$(dirname "${0}")")"
SRC_DIR="$(dirname "${SELF_DIR}")"
cd "${SRC_DIR}" || exit $?

## Cleanup

# Empty directories
find "${SRC_DIR}" \( -name 'defaults' -o -name 'tasks' -o -name 'files' -o -name 'templates' \) -print0 | xargs -0 rmdir 2>/dev/null

# Ansible artefacts
find "${SRC_DIR}" -name '*.retry' -delete

# Python artefacts
find "${SRC_DIR}" -name '__pycache__' -print0 | xargs -0 rm -rf 2>/dev/null
