---
#  -*- mode:yaml; tab-width:2; intent-tabs-mode:nil; -*- ex: set filetype=yaml tabstop=2 expandtab:
## IPv6 setup

- name: "IPv6 setup"
  tags:
    - ipv6
    - always
  include_tasks:
    file: "{{ IPV6_ENABLE|bool | ternary('enable.yaml', 'disable.yaml') }}"
